[2016-05-09 10:24:10,352] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:24:10,352] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:24:10,980] {models.py:296} INFO - Loaded DAG <DAG: update_progress>
[2016-05-09 10:24:27,795] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:24:27,795] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:24:28,006] {models.py:296} INFO - Loaded DAG <DAG: update_progress>
[2016-05-09 10:24:28,493] {models.py:1001} INFO - 
--------------------------------------------------------------------------------
Attempt 1 out of 2
--------------------------------------------------------------------------------

[2016-05-09 10:24:28,607] {models.py:1041} INFO - Executing <Task(PythonOperator): load_new_data> on 2016-05-09 00:00:00
[2016-05-09 10:24:28,618] {python_operator.py:66} INFO - Done. Returned value was: None
[2016-05-09 10:27:16,379] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:27:16,379] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:27:16,433] {models.py:296} INFO - Loaded DAG <DAG: update_progress>
[2016-05-09 10:27:18,265] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:27:18,265] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:27:18,332] {models.py:296} INFO - Loaded DAG <DAG: update_progress>
[2016-05-09 10:27:18,368] {models.py:979} INFO - Task <TaskInstance: update_progress.load_new_data 2016-05-09 00:00:00 [success]> previously succeeded on 2016-05-09 10:24:29
[2016-05-09 11:02:32,729] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 11:02:32,729] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 11:02:32,806] {models.py:296} INFO - Loaded DAG <DAG: update_progress>
[2016-05-09 11:02:46,345] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 11:02:46,346] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 11:02:46,719] {models.py:296} INFO - Loaded DAG <DAG: update_progress>
[2016-05-09 11:02:47,470] {models.py:1001} INFO - 
--------------------------------------------------------------------------------
Attempt 1 out of 2
--------------------------------------------------------------------------------

[2016-05-09 11:02:47,489] {models.py:1041} INFO - Executing <Task(PythonOperator): load_new_data> on 2016-05-09 00:00:00
[2016-05-09 11:02:47,498] {python_operator.py:66} INFO - Done. Returned value was: None
