[2016-05-09 10:24:09,763] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:24:09,763] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:24:09,961] {models.py:296} INFO - Loaded DAG <DAG: update_progress>
[2016-05-09 10:24:26,554] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:24:26,555] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/update_progresses.py
[2016-05-09 10:24:27,378] {models.py:296} INFO - Loaded DAG <DAG: update_progress>
[2016-05-09 10:24:27,633] {models.py:1001} INFO - 
--------------------------------------------------------------------------------
Attempt 1 out of 2
--------------------------------------------------------------------------------

[2016-05-09 10:24:27,803] {models.py:1041} INFO - Executing <Task(PythonOperator): load_new_data> on 2016-04-02 00:00:00
[2016-05-09 10:24:27,814] {python_operator.py:66} INFO - Done. Returned value was: None
